### ISSUE TITLE
Review: emberjs/rfcs#391

### ISSUE THREAD

**Issue by rwjblue** [intercom/ember-href-to#100]
Just wanted to ping y'all about https://github.com/emberjs/rfcs/pull/391 which (to my knowledge) would largely make the work that this addon does part of Ember itself.

Would love your thoughts and input over there on the RFC...

**Comment by derrabauke** [comment]
If you came across this issue you may want to go on here:
- [emberjs/rfcs#391 (current working link)](https://rfcs.emberjs.com/id/0391-router-helpers)
- [ember-router-helpers](https://github.com/rwjblue/ember-router-helpers)
