### ISSUE TITLE
v2.0 broke import of hrefTo function

### ISSUE THREAD

**Issue by jamesarosen** [intercom/ember-href-to#105]
The [change from v1.15.1 to v2.0.0](https://github.com/intercom/ember-href-to/compare/v1.15.1...v2.0.0) removed
```js
// addon/helpers/href-to.js
export { hrefTo };
```

That means it's not possible to do `import { hrefTo } from 'ember-href-to/helpers/href-to'`. It also means the [reexport from `app/`](https://github.com/intercom/ember-href-to/blob/master/app/helpers/href-to.js#L1) is broken.

**Comment by rahsheen** [comment]
Any updates on this? Was this done for a reason? Is there a fix/work-around for those using this import?

**Comment by GavinJoyce** [comment]
@rahsheen I suspect that this was a mistake. Perhaps you might be interested in creating a PR to fix?

**Comment by janwerkhoven** [comment]
Reverted back to `"ember-href-to": "^1.15.1",` and import work again.

Thanks for finding and raising this @jamesarosen .

**Comment by GavinJoyce** [comment]
`3.1.0` has been published which includes a fix for this.

If you can, you should use Ember's router service's `urlFor` for this instead:

https://api.emberjs.com/ember/3.8/classes/RouterService/methods/urlFor?anchor=urlFor

**Comment by janwerkhoven** [comment]
Thanks for the fix @GavinJoyce .

TIL: Ember has `urlFor` 👍
