### ISSUE TITLE
href-to helper doesn't recompute when query params change

### ISSUE THREAD

**Issue by jordpo** [intercom/ember-href-to#131]
I'm using ember-source 3.20 and started noticing an issue where the `service:-routing. generateURL` returns a URL with query params appended if the route where you are loading the page on has query params already in the URL, even if the usage of `href-to` in the template does not specify any query params. This is weird behavior and is causing bugs in our application that has a lot of filtering. The flow now for a user:

1) filters by something
2) reloads the page with the query param in the URL
3) the side nav link has hardcoded the query param in the href

The [`service:router. urlFor`](https://api.emberjs.com/ember/3.19/classes/RouterService/methods/urlFor?anchor=urlFor) seems to be the better way to go and fixes the issue with the non-wanted query params in the href.

**Comment by jordpo** [comment]
I created a working public gist that we are going to use locally for the time being to fix the issue. 

https://gist.github.com/jordpo/94af6f864ffad1928513f123070d039f

Minus the TS, want me to open a PR?

**Comment by GavinJoyce** [comment]
How does `<LinkTo>` behave in your scenario? `href-to` attempts to behave as closely as possible to `LinkTo`

**Comment by jordpo** [comment]
`<LinkTo>` has the same unexpected behavior.

I created a repo with the comparison between `<LinkTo>`, `href-to`, and my alternative helper `href-to-fix`. If you load the app at `http://localhost:4200/?q=helloworld` you can see the `href` for the first two be `/?q=helloworld` and for the helper with my fix, the href is `/`.

Since I provided no query params to either the component or the helpers, I would expect no query params to be present in the resulting href attributes. That seems like a reasonable expectation and like I said causes bugs in production code where a route is loaded with unexpected query params. 

Here is the link for my repo that you can pull down and see https://github.com/jordpo/link-to-qp-sitickiness.

**Comment by GavinJoyce** [comment]
I believe that this is the expected behaviour of `<LinkTo>`, and by extension, `{{href-to}}`: 

https://guides.emberjs.com/release/routing/query-params/#toc_sticky-query-param-values

**Comment by jordpo** [comment]
Thanks. I understand the stickiness about query params and just assumed that had to do with the controller being a singleton. It's interesting that the link href is also updated though not sure I see the value of that since the controller preserves the query param values when exiting the route unless you explicitly reset them.

How would you clear a query param? When we exit the route we set the query params back to the defaults but the link href has the original query param that the app loaded with in it. So any subsequent visit to that page via the original link will contain that original query param even when we don't want it to.

**Comment by GavinJoyce** [comment]
I'm not sure, it's been a little while since I've worked with query params. Perhaps ask in Ember Discord?

**Comment by GavinJoyce** [comment]
> How would you clear a query param?

The [docs](https://guides.emberjs.com/release/routing/query-params/#toc_sticky-query-param-values) seem to cover that:

<img width="765" alt="Screenshot 2020-07-29 at 23 05 55" src="https://user-images.githubusercontent.com/2526/88858569-1604f000-d1f0-11ea-8f3a-1305e732b991.png">

**Comment by jordpo** [comment]
So I pushed an update to my repo highlighting an important difference in behavior between `<LinkTo>` and `href-to`. The former does recompute when the query params are changed in the `resetController` hook while `href-to` doesn't recompute. Do we need to add a recompute to the helper based on query params changing like that?

**Comment by jordpo** [comment]
Also confirmed that the `href` on `<LinkTo>` changes any time the query param changes on the route. So it does feel like a recompute issue for the helper.

**Comment by GavinJoyce** [comment]
Thanks, it seems like it. Perhaps you might add a failing test as a first step?

**Comment by jordpo** [comment]
Yeah will do. Probably not tonight but will try to open a PR in the next day or so.

**Comment by jordpo** [comment]
I updated the issue subject to be clearer.

**Comment by GavinJoyce** [comment]
nice one, thanks

**Comment by jordpo** [comment]
@GavinJoyce opened a PR with the test and the fix. I don't like using `observer` but not sure we have any other option here.

**Comment by jordpo** [comment]
@GavinJoyce would the next step do a major version release since the update has breaking changes?

**Comment by GavinJoyce** [comment]
Yes, I'll do that soon.

**Comment by jordpo** [comment]
Awesome - thanks!
