### ISSUE TITLE
Inquiry on Intercom White Labeling Options

### ISSUE THREAD

**Issue by Marys-Team** [intercom/ember-href-to#159]
Dear Intercom Team,

We are interested in white labeling options for Intercom. Can you provide information on customization possibilities, including our logo, colors, and visual elements? Is it possible to use our own domain? Can we remove or minimize Intercom branding in the user interface?

Thank you for your attention. We look forward to your response.

Best regards,
Marys-Team.

**Comment by 22a** [comment]
Hi @Marys-Team, this sounds like a question about behaviour of the Intercom product as opposed to the `intercom/ember-href-to` repo/addon itself. If you can, please reach out to our team via the messenger on the bottom right corner of https://www.intercom.com/

<img width="1840" alt="screenshot of intercom website with arrow pointing to messenger in bottom right hand corner" src="https://github.com/intercom/ember-href-to/assets/7144173/00d9216d-3b8d-4b90-a30c-b2489d621841">
