### ISSUE TITLE
Is it possible to add classes and data attributes?

### ISSUE THREAD

**Issue by therealbenhogan** [intercom/ember-href-to#29]
Hi,

I know you don't get automatic active class bindings as you with {{#link-to}} but is it possible to add class names and data attributes?

**Comment by oskarrough** [comment]
href-to is a helper, not a component. So just do like you normally would in HTML.

```handlebars
<a href="{{href-to 'application'}}" class="MyClass" data-whatever="pizza">Go to home</a>
```

**Comment by therealbenhogan** [comment]
Sorry - should have mentioned I have already tried this - the class and data attributes are not rendered when you do this.....

**Comment by oskarrough** [comment]
That's weird, they do render here. Could you post a full code snippet?

**Comment by therealbenhogan** [comment]
Hi, 

Sorry - please bear with me - not sure how to show you everything short of putting the complete app up.

This is my mark up example 

<a href="{{href-to 'students' class="hello" data-whatever="whatever" data-any="something"}}">Students</a>

The link displays and works fine, but if I inspect the html in Firefox, the class and data attributes are just missing ?? 

Is there anything else you need?

**Comment by therealbenhogan** [comment]
Hi, 

Very sorry - I totally ignored the fact that you had the class and data attributes outside of the {{href}} block - apologies !!!!

**Comment by oskarrough** [comment]
No worries, had the exact same misunderstanding when I first refactored from link-to to href-to…
