### ISSUE TITLE
Active class

### ISSUE THREAD

**Issue by therealbenhogan** [intercom/ember-href-to#30]
Hi,

I'm using the helper in my navigation - all ok, and when rendering my nav component (assuming a class of nav-bar see below) I can give the target value an active class. 

What I'm not sure about is how to give an item in the menu the active class when the link to that page has been clicked elsewhere within the app - for example from within the content, or in the footer etc.

Do you have any ideas on this?

Many thanks!

nav-bar-component.js

    didInsertElement() {
      this._super(...arguments);
      this.$('.nav-bar a').on('click',function(){
         $('.nav-bar a').removeClass('active');
         $(this).parents('li').children('a').addClass('active');
      });
    }

**Comment by oskarrough** [comment]
This is where you should use the default {{link-to}}` component, as I see it.

**Comment by therealbenhogan** [comment]
Many thanks for getting back.

The problem with that is how to render a {{link-to}} component in content that's coming from (eg) the admin where a site owner would want to link to other pages in the site ... I also problems with my nav-bar component giving the parent elements the active class - but that's more down to my poor jquery no doubt!

**Comment by oskarrough** [comment]
For the active parent class, check out https://github.com/alexspeller/ember-cli-active-link-wrapper

**Comment by therealbenhogan** [comment]
Many thanks for this pointer - much appreciated!
