### ISSUE TITLE
More details on lightweight nature

### ISSUE THREAD

**Issue by ianpetzer** [intercom/ember-href-to#6]
Hi,

Would it be possible to supply some information on how this is lightweight compared to the link-to helper?

I know that when I looked at my app in the Ember inspector, I'm was a little surprised at how much render time the link-to components take but I don't really understand why.

I'd be really interested to get some perspective on how the {{ember-href-to}} component is different to the {{link-to}}

**Comment by GavinJoyce** [comment]
I've just added some details to the [readme](https://github.com/intercom/ember-href-to/blob/master/README.md). Here are some performance tests results: https://github.com/GavinJoyce/ember-performance/pull/1

**Comment by ianpetzer** [comment]
Ah that is awesome.

Thanks!
