### ISSUE TITLE
Handle clicks for <a> components

### ISSUE THREAD

**Issue by samselikoff** [intercom/ember-href-to#64]
Awesome addon!

I have a use case for allowing the initializer to intercept clicks from an Ember.Component. We are using styleguide components like `{{em-title}}`, `{{em-button}}` and so on. I want an element that looks like a button but functions like a link. The public API looks like this:

``` hbs
{{#em-button style='link' href=(href-to 'about')}}
  Learn more
{{/em-button}}
```

Because of the `link` style, the `tagName` is set to `<a>` and `href` is bound. Everything works and the output is correct, but `ember-href-to`'s global event handler is ignored because of [this line](https://github.com/intercom/ember-href-to/blob/master/app/instance-initializers/browser/ember-href-to.js#L21) (it ignores all `.ember-view`s).

If you think this is legitimate I'm happy to work on a PR. What would be the approach? It seems that if you're using `href-to` you're opting-in to this library handling the click event. Could `href-to` set some property on the component instance that could be checked, which would allow the event handler to handle the click?

**Comment by GavinJoyce** [comment]
Hey @samselikoff.

Thanks for this, it's a case that we should handle. Perhaps we could check for the presence of an attribute on a component element? Something like `data-href-to-enabled`? This would allow you to opt in a particular component to the `href-to` click handler

**Comment by GavinJoyce** [comment]
Thinking about this a little more, the reason that we ignore clicks on elements which have an `ember-view` class is so that we don't interfere with the default behavior of `link-to` components. Perhaps we could lookup the component (if any) associated with the click target and ignore the click of the component is an instance of `LinkComponent`?

**Comment by samselikoff** [comment]
Hm, well you'd also want to ignore clicks on a

```
{{my-component on-click=(action 'foo')}}
```

right?

What if `href-to` can set a `hrefToEnabled` to `true` on the component, then the initializer can lookup the component instance by `id` and see if it has that property? Then you wouldn't need a new opt-in API.

**Comment by GavinJoyce** [comment]
Are there legitimate cases for using a component with an `A` tag and href, which also happen to have a click handler? If not, I don't think the example above is something that we need to handle. We currently only add a click handler to anchors

**Comment by samselikoff** [comment]
Ah, since the handler only runs if `href` equals something. (Do we need to ignore if `href='#'`?).

In this case I think you're right, we can just let `LinkComponent` pass through and handle all others. I am happy to PR if this sounds right.

**Comment by GavinJoyce** [comment]
We only add the `href-to` handler to [anchors](https://github.com/intercom/ember-href-to/blob/master/app/instance-initializers/browser/ember-href-to.js#L35). I'm not sure about the `href='#'` case, I assume that we [don't recognize that URL](https://github.com/intercom/ember-href-to/blob/master/app/instance-initializers/browser/ember-href-to.js#L43) so we don't process it

> we can just let LinkComponent pass through and handle all others. I am happy to PR if this sounds right.

Yes, I think that sounds right. We should be able to lookup the component instance at click time and skip it if it already has a click handler.
