### ISSUE TITLE
[QUESTION] target attribute

### ISSUE THREAD

**Issue by roruva** [intercom/ember-href-to#70]
How to use target attribute in tag **a** ?
I try this:
`<a href="{{href-to "nameRoute.nestedRoute" user.username}}" target="_blank"> {{user.username}} </a>`

But it does not work.

**Comment by GavinJoyce** [comment]
@roruva you seem to be mixing double quotes. Try this:

```
<a href="{{href-to 'nameRoute.nestedRoute' user.username}}" target="_blank"> {{user.username}} </a>
```
