### ISSUE TITLE
Is it still needed with Glimmer 2 and Ember 2.12?

### ISSUE THREAD

**Issue by johnunclesam** [intercom/ember-href-to#72]
Is it still needed with Glimmer 2 and Ember 2.12?

**Comment by jasonmit** [comment]
Yes. What makes you think it wouldn't be?

**Comment by GavinJoyce** [comment]
`href-to` is only useful if performance is a concern for your app. If you don't have many links, `link-to` is fine to use

As `href-to` does much less work than `link-to`, it is always going to be much faster than `link-to`. The [router service](https://github.com/emberjs/rfcs/pull/95) is being implemented and it will bring a `url-for` helper which will remove the need for this addon, we'll work on deprecating `href-to` once it lands
