### ISSUE TITLE
Modernize the addon

### ISSUE THREAD

**Issue by GavinJoyce** [intercom/ember-href-to#88]
<img width="788" alt="screen shot 2017-10-20 at 12 06 08" src="https://user-images.githubusercontent.com/2526/31818223-15c03314-b58f-11e7-9fb7-0f21ce9d3560.png">
<img width="817" alt="screen shot 2017-10-20 at 12 09 06" src="https://user-images.githubusercontent.com/2526/31818302-7fc7ce52-b58f-11e7-80e4-9486e053cce1.png">

**Comment by locks** [comment]
- Modules API
  - Issue https://github.com/intercom/ember-href-to/issues/84
  - PR https://github.com/intercom/ember-href-to/pull/89
- Router Service
  - Issue https://github.com/intercom/ember-href-to/issues/82
